# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
name: R CI/CD test #R-CMD-check

on:
  push:
    # branches: [main, master, develop]
    paths-ignore:
      - '**.md'  # prevent md files (e.g., README.md) in any repo dir from trigering workflow
      - '**.bib'
      - '**.ya?ml'  # captures both .yml and .yaml
      - '**.png'
      - '**.Rmd'
      - 'LICENSE'
      - '.gitignore'
      - '.gitattributes'
  pull_request:
    branches: [master, develop]
    paths-ignore:
      - '**.md'
      - '**.bib'
      - '**.ya?ml'
      - '**.png'
      - '**.Rmd'
      - 'LICENSE'
      - '.gitignore'
      - '.gitattributes'
  workflow_dispatch:  # also allow manual trigger, for testing purposes

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}

    env:
      #GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }} 
      R_KEEP_PKG_SOURCE: yes
    
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            rcmdcheck
            devtools

      - uses: r-lib/actions/check-r-package@v2

      - name: Build and validate models - USEEIOv2.0-411 detail model with waste disaggregation
        if: always()
        run: |
          require(devtools)
          devtools::load_all()
          m <- useeior::buildModel("USEEIOv2.0-411")
          useeior::printValidationResults(m)
        shell: Rscript {0}

      - name: Build and validate models - USEEIOv2.0-i-411 detail industry model with waste disaggregation
        if: always()
        run: |
          require(devtools)
          devtools::load_all()
          m <- useeior::buildModel("USEEIOv2.0-i-411")
          useeior::printValidationResults(m)
        shell: Rscript {0}
      
      - name: Build and validate models - USEEIOv2.0 industry model
        if: always()
        run: |
          require(devtools)
          devtools::load_all()
          m <- useeior::buildModel("USEEIOv2.0-i-GHG")
          useeior::printValidationResults(m)
        shell: Rscript {0}
      
      - name: Build and validate models - USEEIOv2.0 summary model
        if: always()
        run: |
          require(devtools)
          devtools::load_all()
          m <- useeior::buildModel("USEEIOv2.0-s-GHG")
          useeior::printValidationResults(m)
        shell: Rscript {0}
      
      - name: Build and validate models - USEEIOv2.0.1-411 detail model with waste disaggregation
        if: always()
        run: |
          require(devtools)
          devtools::load_all()
          m <- useeior::buildModel("USEEIOv2.0.1-411")
          useeior::printValidationResults(m)
        shell: Rscript {0}

      - name: Build and validate models - USEEIOv2 - integrated hybrid
        if: always()
        run: |
          require(devtools)
          devtools::load_all()
          m <- useeior::buildModel("USEEIOv2.0-GHG-NGCombustion")
          useeior::printValidationResults(m)
        shell: Rscript {0}

      - name: Build and validate models - GAEEIOv1.0-s-WAT-12 two-region model
        if: always()
        run: |
          require(devtools)
          devtools::load_all()
          m <- useeior::buildModel("GAEEIOv1.0-s-WAT-12")
          useeior::print2RValidationResults(m)
        shell: Rscript {0}

      - name: Build and validate models - USEEIOv2.0-s-GHG-19-IF summary model with import factors
        if: always()
        run: |
          require(devtools)
          devtools::load_all()
          m <- useeior::buildModel("USEEIOv2.0-s-GHG-19-IF")
          useeior:::validateImportFactorsApproach(m)
        shell: Rscript {0}

      # - name: Build and validate models - GAEEIOv1.0-75-GHG-19 two-region disaggregated model
      #   if: always()
      #   run: |
      #     require(devtools)
      #     devtools::load_all()
      #     m <- useeior::buildModel("GAEEIOv1.0-75-GHG-19")
      #     useeior::print2RValidationResults(m)
      #   shell: Rscript {0}

      #- name: Show testthat output
      #  if: always()  # step will run even if previous steps fail
      #  run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
      #  shell: bash

      - name: Upload check results
        if: failure()  # if any of the previous steps fail, export a log
        uses: actions/upload-artifact@main
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check    
    
